"""Models for the chatterloop app.

Django's app registry imports `<app>.models` and nothing else, so a model
defined in another module is never registered. This file is what makes
`external_models` visible to the ORM.

The split is worth being able to see at a glance: everything imported from
`external_models` is a projection of a table `user_service` owns and Neon must
not migrate, while everything DEFINED below is Neon's own row, in Neon's own
database. `chatterloop/routers.py` enforces that split by model name.
"""

from django.db import models

from llm.models import Agent
from neon.utils.crypto import decrypt, encrypt
from neon.utils.identifiers import new_id
from organization.models import Organization

# Aliased, and not for style. `Account` is a name BOTH sides of this split use:
# `user.Account` is Neon's own row, `external_models.Account` is the projection
# of chatterloop's `user_account`. While this was imported bare, it sat above
# the `from .external_models import ...` block and quietly won the name - so
# `from chatterloop.models import Account` handed out Neon's table while
# reading as chatterloop's, and core/services/chatterloop_identity.py spent its
# life looking up sign-ins in the wrong database.
from user.models import Account as NeonAccount

from .external_models import (  # noqa: F401
    Account as ChatterloopAccount,
    Bot,
    Entity,
    EntityPermission,
    Realm,
    RealmMember,
    Token,
)

__all__ = [
    "ChatterloopAccount",
    "Bot",
    "Entity",
    "EntityPermission",
    "Realm",
    "RealmMember",
    "Token",
    "ChatterloopBot",
    "ChatterloopToken",
]


def new_uuid():
    """Default for this app's ids. See neon.utils.identifiers.new_id.

    Delegates rather than being deleted: migration 0001 names this function by
    import path, and a migration whose default cannot be imported will not
    load.
    """
    return new_id()


class ChatterloopBot(models.Model):
    """A bot Neon minted on chatterloop, and the agent that answers for it.

    WHY NEON KEEPS ITS OWN ROW
    --------------------------
    `bot_bot` knows a bot's name, handle and owner. It does not and must not
    know which Neon organization provisioned it, which agent answers its
    mentions, or which Neon account to blame - that is Neon's domain model, and
    putting it in another service's table would be Neon migrating a schema it
    does not own.

    `entity_id` is the join between the two, stored as a plain column rather
    than a foreign key. Django cannot enforce or join an FK across database
    connections, which is the same reason `user.Account` mirrors rather than
    points at `user_account`.

    PROVISIONING IS NOT ATOMIC ACROSS TWO DATABASES, SO ORDER MATTERS
    ----------------------------------------------------------------
    There is no transaction spanning Neon's database and chatterloop's. If
    chatterloop were written first and Neon's record second, a failure in
    between would leave a live bot with a live credential that Neon has no row
    for - unrevokable, because nothing knows it exists.

    So the order is inverted: Neon generates the ids, writes this row with
    `status=PROVISIONING`, and only then writes chatterloop. A failure now
    leaves a Neon row that names exactly which chatterloop entity to clean up,
    which is recoverable. A row stuck in PROVISIONING is the visible symptom.
    """

    STATUS_PROVISIONING = "provisioning"
    STATUS_ACTIVE = "active"
    STATUS_FAILED = "failed"
    STATUS_DEACTIVATED = "deactivated"
    STATUS_CHOICES = [
        (STATUS_PROVISIONING, "Provisioning"),
        (STATUS_ACTIVE, "Active"),
        (STATUS_FAILED, "Failed"),
        (STATUS_DEACTIVATED, "Deactivated"),
    ]

    id = models.CharField(max_length=150, primary_key=True, default=new_uuid)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="chatterloop_bots"
    )
    created_by = models.ForeignKey(
        NeonAccount,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="minted_bots",
    )

    # The chatterloop entity this bot IS. Generated by Neon before minting, so
    # it is known even if the chatterloop write never completes.
    entity_id = models.CharField(max_length=40, unique=True, db_index=True)
    # The `bot_bot` row id, for the same reason.
    bot_id = models.CharField(max_length=40, unique=True)

    name = models.CharField(max_length=80)
    handle = models.CharField(max_length=50)
    description = models.TextField(blank=True, default="")

    # Whose name the bot acts under. NULL means the minting user's own
    # chatterloop identity; a value means a connected page.
    #
    # SET_NULL rather than CASCADE: disconnecting a page deactivates its bots
    # and revokes their tokens (see core/views.py), and the bot row must
    # survive that so the history of what it did is still explicable.
    owner_entity_id = models.CharField(max_length=40)
    connected_account = models.ForeignKey(
        "core.ConnectedAccount",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="bots",
    )

    # What answers when this bot is mentioned. SET_NULL because deleting an
    # agent should not silently delete a live chatterloop identity - the bot
    # stops having anything to say, which the UI can show, rather than
    # vanishing.
    agent = models.ForeignKey(
        Agent,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="chatterloop_bots",
    )

    # Which model generates its replies. Explicit rather than "the
    # organization's first": a bot answers unattended, so the choice between a
    # cheap model and an expensive one is a standing decision somebody should
    # make once and be able to see, not one re-derived per message from
    # whatever row happens to sort first.
    #
    # SET_NULL, and a bot with no model does not answer - it says so on the
    # Bots screen rather than failing silently in a worker.
    model = models.ForeignKey(
        "llm.Model",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="chatterloop_bots",
    )

    # Which API key this bot's replies are billed to. NULL means "whatever the
    # organization uses by default for this model's provider", which is what
    # every bot did before several keys per provider were allowed.
    #
    # Assignable per bot so a customer-facing bot's spend can be separated from
    # everything else's, or so a noisy one can be given its own rate limit -
    # without every bot needing its own key.
    provider_credential = models.ForeignKey(
        "organization.ProviderCredential",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="bots",
        help_text="Leave empty to use the organization's default for this provider.",
    )

    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default=STATUS_PROVISIONING
    )

    # Whether this bot should be LISTENING right now. Separate from `status`,
    # and the distinction is the point:
    #
    #   status  - lifecycle. Does this bot exist and work at all? Deactivating
    #             revokes every token, so coming back needs a new one.
    #   online  - runtime. Should a supervisor hold an event stream for it
    #             right now? Toggling costs nothing and is instantly
    #             reversible: the identity, the token and the agent binding all
    #             survive.
    #
    # A deactivated bot is also offline; an offline bot is not deactivated.
    # Without this, the only way to stop a bot answering was to revoke its
    # credential - far too heavy for "pause it over the weekend".
    is_online = models.BooleanField(
        default=True,
        help_text="Whether a supervisor should hold an event stream for this bot.",
    )
    # When the switch was last flipped, so the UI can say "offline since
    # Tuesday" rather than just "offline".
    online_changed_at = models.DateTimeField(null=True, blank=True)

    # WHETHER THIS BOT WILL TALK TO OTHER BOTS.
    #
    # Off by default, and deliberately so: two bots that answer each other
    # never run out of things to say. Every threaded reply re-addresses the
    # other, so there is no natural end - only the models deciding they are
    # finished, which is a judgement they may not make.
    #
    # On, the bot answers bot-authored triggers and the hourly cap is replaced
    # by a per-conversation TURN BUDGET, so a collaboration that does not end
    # itself still ends. Both bots need it on: each one checks its own flag, so
    # one bot with it off is enough to stop the exchange - which is also how
    # you stop one that is running.
    #
    # Changing this on a bot that is ALREADY ONLINE works: the supervisor's
    # sweep reconfigures the live policy (BotWorker.refresh). It did not at
    # first, and the failure was silent in the worst way - the database said
    # on, the running bot behaved as off, and the natural order to do things
    # in (switch the bot on, then tick the box) was the one that broke.
    allow_bot_conversations = models.BooleanField(
        default=False,
        help_text=(
            "Let this bot reply to other bots, so two bots can work through a "
            "task together. Bounded by a per-conversation turn budget."
        ),
    )

    # Why it stopped. Shown to the user, because "my bot went quiet" with no
    # explanation is the single most expensive kind of failure here.
    status_reason = models.TextField(blank=True, default="")

    # What GET /v1/whoami answered. Stored because a handle Neon THINKS it set
    # and the handle developer_service resolves can differ - see
    # provisioning.verify() - and when they do, mention matching silently never
    # fires.
    verified_handle = models.CharField(max_length=50, blank=True, default="")
    last_verified_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["organization", "handle"], name="unique_bot_handle_per_org"
            ),
        ]

    @property
    def is_live(self):
        return self.status == self.STATUS_ACTIVE

    @property
    def can_answer(self):
        """Whether this bot is CONFIGURED to produce a reply.

        Three things have to hold, and each fails silently on its own: the bot
        has to be live, it needs an agent to answer AS, and a model to answer
        WITH. Checked here so the UI can say which one is missing instead of
        the user discovering it from a bot that receives events and never
        speaks.

        Deliberately NOT about being online. A bot that is switched off is
        correctly silent, and conflating the two would report a configuration
        problem where there is none.
        """
        return bool(self.is_live and self.agent_id and self.model_id)

    @property
    def should_run(self):
        """Whether a supervisor ought to be holding a stream for this bot.

        The same condition `Supervisor._candidates()` filters on, expressed
        once so the UI and the runtime cannot disagree about what "should be
        running" means.
        """
        return bool(self.can_answer and self.is_online)

    @property
    def handle_mismatch(self):
        """Whether chatterloop resolves a different handle than Neon set.

        A bot configured with the wrong handle matches no mentions and nothing
        in any log says why, so this is worth surfacing rather than assuming.
        """
        return bool(self.verified_handle) and self.verified_handle != self.handle

    def __str__(self):
        return f"@{self.handle} ({self.organization.name})"


class ChatterloopToken(models.Model):
    """The credential a bot authenticates with.

    NEON IS THE SOLE HOLDER OF THE PLAINTEXT
    ----------------------------------------
    chatterloop stores only `token_hash`, a plain unsalted SHA-256 of the whole
    token string, and hands the token back exactly once at issue. The bot
    runtime has to present it on every reconnect, so Neon keeps it - encrypted
    at rest with the same Fernet key as provider credentials
    (neon/utils/crypto.py).

    Encrypted rather than hashed because it must be RECOVERABLE: this protects
    a leaked database dump, not a compromised application, and those are
    different threats. If `secret_encrypted` becomes unreadable - a rotated key
    with no fallback - the only remedy is minting a replacement token, because
    nothing else anywhere has the value.

    `prefix` is NOT a secret. It travels in the clear inside every token, which
    is exactly how verification finds the row with one indexed lookup.
    """

    id = models.CharField(max_length=150, primary_key=True, default=new_uuid)
    bot = models.ForeignKey(
        ChatterloopBot, on_delete=models.CASCADE, related_name="tokens"
    )

    # The `entity_token` row id, generated by Neon before minting.
    token_id = models.CharField(max_length=40, unique=True)
    prefix = models.CharField(max_length=16, unique=True, db_index=True)
    secret_encrypted = models.TextField()

    name = models.CharField(max_length=120)
    scopes = models.JSONField(default=list)

    expires_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)
    # NULL means the chatterloop write never completed - see ChatterloopBot's
    # note on ordering. Such a row is an incomplete provision, not a usable
    # credential.
    provisioned_at = models.DateTimeField(null=True, blank=True)
    last_verified_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    @property
    def is_live(self):
        return self.revoked_at is None and self.provisioned_at is not None

    @property
    def token(self):
        """The full `clt_<prefix>_<secret>` string.

        Reassembled rather than stored whole: the prefix is a plain indexed
        column used for lookup and display, and only the secret half needs
        protecting.
        """
        secret = decrypt(self.secret_encrypted)
        return f"clt_{self.prefix}_{secret}" if secret else ""

    def set_secret(self, secret):
        self.secret_encrypted = encrypt(secret)

    def __str__(self):
        return f"{self.name} (clt_{self.prefix}…)"
