# Generated by Django 5.2.5 on 2025-11-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='llm_api_key',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
