# Generated by Django 5.2.5 on 2026-09-13 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0009_org_scoped_tools_and_roles'),
        ('organization', '0002_organization_llm_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('is_embedding_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_credentials', to='organization.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='llm.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'service'), name='unique_credential_per_org_service'), models.UniqueConstraint(condition=models.Q(('is_embedding_default', True)), fields=('organization',), name='one_embedding_default_per_org')],
            },
        ),
    ]
