# Generated by Django 5.2.5 on 2026-09-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0011_alter_agent_uuid_alter_model_uuid_alter_service_uuid'),
        ('organization', '0004_alter_member_id_alter_organization_access_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='providercredential',
            name='unique_credential_per_org_service',
        ),
        migrations.AddField(
            model_name='providercredential',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='providercredential',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_credential_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='providercredential',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization', 'service'), name='one_default_credential_per_org_service'),
        ),
    ]
