# Generated by Django 5.2.5 on 2026-09-13 09:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0040_chatterloop_identity_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('provider', models.CharField(choices=[('chatterloop', 'Chatterloop')], default='chatterloop', max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=40)),
                ('external_type', models.CharField(choices=[('user', 'User'), ('realm', 'Realm')], default='realm', max_length=20)),
                ('external_username', models.CharField(blank=True, default='', max_length=150)),
                ('external_name', models.CharField(blank=True, default='', max_length=255)),
                ('external_profile', models.CharField(blank=True, default='none', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_verified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disconnected_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to='user.account')),
            ],
        ),
        migrations.DeleteModel(
            name='TPAuthentication',
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['account', 'provider'], name='core_connec_account_c1f7ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectedaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('provider', 'external_id'), name='one_live_claim_per_external_identity'),
        ),
    ]
