# Generated by Django 5.2.5 on 2026-09-13 12:03

import chatterloop.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_connected_accounts'),
        ('llm', '0010_knowledgedocument'),
        ('organization', '0003_provider_credentials'),
        ('user', '0040_chatterloop_identity_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.CharField(max_length=500)),
                ('is_active', models.BooleanField()),
                ('is_verified', models.BooleanField()),
                ('join_type', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'user_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('handle', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('profile', models.CharField(default='none', max_length=500)),
                ('is_system', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'bot_bot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'entity_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntityPermission',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=150)),
                ('effect', models.CharField(max_length=10)),
                ('reason', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'entity_entitypermission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('realm_id', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.TextField(null=True)),
                ('profile', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=150)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'community_realm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RealmMember',
            fields=[
                ('member_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=150, null=True)),
                ('role', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'community_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('prefix', models.CharField(max_length=16, unique=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('last_used_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_int', models.PositiveIntegerField(null=True)),
                ('rate_limit_type', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'entity_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatterloopBot',
            fields=[
                ('id', models.CharField(default=chatterloop.models.new_uuid, max_length=150, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('bot_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('handle', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('owner_entity_id', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('failed', 'Failed'), ('deactivated', 'Deactivated')], default='provisioning', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('verified_handle', models.CharField(blank=True, default='', max_length=50)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatterloop_bots', to='llm.agent')),
                ('connected_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='core.connectedaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minted_bots', to='user.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatterloop_bots', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatterloopToken',
            fields=[
                ('id', models.CharField(default=chatterloop.models.new_uuid, max_length=150, primary_key=True, serialize=False)),
                ('token_id', models.CharField(max_length=40, unique=True)),
                ('prefix', models.CharField(db_index=True, max_length=16, unique=True)),
                ('secret_encrypted', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='chatterloop.chatterloopbot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatterloopbot',
            constraint=models.UniqueConstraint(fields=('organization', 'handle'), name='unique_bot_handle_per_org'),
        ),
    ]
