# Generated by Django 5.2.5 on 2026-09-13 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterloop', '0001_initial'),
        ('llm', '0010_knowledgedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatterloopbot',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatterloop_bots', to='llm.model'),
        ),
    ]
