# Generated by Django 5.2.5 on 2026-09-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterloop', '0002_chatterloopbot_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatterloopbot',
            name='is_online',
            field=models.BooleanField(default=True, help_text='Whether a supervisor should hold an event stream for this bot.'),
        ),
        migrations.AddField(
            model_name='chatterloopbot',
            name='online_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
