# Generated by Django 5.2.5 on 2026-09-13 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterloop', '0003_chatterloopbot_is_online_and_more'),
        ('organization', '0004_alter_member_id_alter_organization_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatterloopbot',
            name='provider_credential',
            field=models.ForeignKey(blank=True, help_text="Leave empty to use the organization's default for this provider.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='organization.providercredential'),
        ),
    ]
