# Generated by Django 5.2.5 on 2026-09-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterloop', '0004_chatterloopbot_provider_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatterloopbot',
            name='allow_bot_conversations',
            field=models.BooleanField(default=False, help_text='Let this bot reply to other bots, so two bots can work through a task together. Bounded by a per-conversation turn budget.'),
        ),
    ]
