# Generated by Django 5.2.5 on 2026-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterloop', '0005_chatterloopbot_allow_bot_conversations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('responds', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'bot_commands',
                'managed': False,
            },
        ),
    ]
