# Generated by Django 5.2.5 on 2026-09-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterloop', '0006_botcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatterloopbot',
            name='control_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
