# Generated by Django 5.2.5 on 2025-11-19 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, unique=True),
        ),
    ]
