# Generated by Django 5.2.5 on 2025-11-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_agent_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='authentication',
            field=models.TextField(blank=True),
        ),
    ]
