# Generated by Django 5.2.5 on 2025-11-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_tool_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='headers_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
