# Generated by Django 5.2.5 on 2025-11-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_tool_headers_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
