# Generated by Django 5.2.5 on 2025-11-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_tool_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='param_type',
            field=models.CharField(choices=[('query', 'Query'), ('route', 'Route'), ('body', 'Body')], default='query'),
        ),
    ]
