# Generated by Django 5.2.5 on 2026-09-13 11:18

import django.db.models.deletion
import llm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0009_org_scoped_tools_and_roles'),
        ('organization', '0003_provider_credentials'),
        ('user', '0040_chatterloop_identity_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.CharField(default=llm.models.new_uuid, max_length=150, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_name', models.CharField(blank=True, default='', help_text='Original filename, if any.', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('vector_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='organization.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='user.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
