"""Store a STRING in the uuid CharFields, not a UUID object.

WHAT THIS CHANGES
-----------------
Only the Python-level `default`. `uuid.uuid4` is a function returning a `UUID`
object, and these are CharFields - so Django wrote text to the database while
handing a freshly created instance a `UUID`. An object and the same row fetched
back therefore compared UNEQUAL, because `Model.__eq__` compares primary keys
directly. See neon/utils/identifiers.py.

WHAT THIS DOES NOT CHANGE
-------------------------
The data and the schema. `str(uuid.uuid4())` produces exactly the 36-character
hyphenated form CharField was already storing, so existing rows are already in
the target format and need no rewriting.

Django only writes a field default into the schema when ADDING a non-null
column; for an existing column the default lives in Python. On PostgreSQL these
operations therefore emit no DDL at all. On SQLite - the test database - Django
rebuilds the table, because SQLite cannot alter a column in place. That rebuild
is a test-only cost.
"""

# Generated by Django 5.2.5 on 2026-09-13 16:37

import neon.utils.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0010_knowledgedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='uuid',
            field=models.CharField(default=neon.utils.identifiers.new_id, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='uuid',
            field=models.CharField(default=neon.utils.identifiers.new_id, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='uuid',
            field=models.CharField(default=neon.utils.identifiers.new_id, unique=True),
        ),
    ]
