# Generated by Django 5.2.5 on 2026-09-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0011_alter_agent_uuid_alter_model_uuid_alter_service_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='knowledge_documents', to='llm.agent'),
        ),
    ]
