# Generated by Django 5.2.5 on 2025-11-17 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm', '0001_initial'),
        ('organization', '0001_initial'),
        ('user', '0008_alter_verification_ver_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('pending_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('message_type', models.CharField(choices=[('ai_reply', 'AI Reply'), ('reply', 'Reply')])),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='llm.agent')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='messenger.conversation')),
                ('deleted_by', models.ManyToManyField(related_name='conversation_deleted', to='user.account')),
                ('receivers', models.ManyToManyField(related_name='conversation_receivers', to='user.account')),
                ('replying_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='messenger.message')),
                ('seeners', models.ManyToManyField(related_name='conversation_seeners', to='user.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
    ]
