# Generated by Django 5.2.5 on 2025-11-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
        ('user', '0009_alter_verification_ver_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversation_deleted_by', to='user.account'),
        ),
    ]
