# Generated by Django 5.2.5 on 2025-11-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_conversation_created_at'),
        ('user', '0012_alter_token_token_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversation_deleted_by', to='user.account'),
        ),
    ]
