# Generated by Django 5.2.5 on 2025-11-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_message_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('ai_reply', 'AI Reply'), ('text', 'Text'), ('reply', 'Reply')]),
        ),
    ]
