# Generated by Django 5.2.5 on 2025-11-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_alter_message_agent_alter_message_sender'),
        ('user', '0022_alter_token_token_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receivers',
            field=models.ManyToManyField(blank=True, null=True, related_name='conversation_receivers', to='user.account'),
        ),
        migrations.AlterField(
            model_name='message',
            name='seeners',
            field=models.ManyToManyField(blank=True, null=True, related_name='conversation_seeners', to='user.account'),
        ),
    ]
