# Generated by Django 5.2.5 on 2025-11-19 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_alter_message_receivers_alter_message_seeners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('context', models.TextField()),
                ('range', models.IntegerField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='messenger.conversation')),
            ],
        ),
    ]
