# Generated by Django 5.2.5 on 2025-12-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='footprint',
            field=models.CharField(blank=True, default=None, null=True, unique=True),
        ),
    ]
