# Generated by Django 5.2.5 on 2026-09-13 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_conversation_footprint'),
        ('user', '0040_chatterloop_identity_projection'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='integration',
            field=models.ForeignKey(blank=True, help_text="The external app/integration this message was sent through, if any. Null means it came from Neon's own native frontend.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='user.token'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
