# Generated by Django 5.2.5 on 2026-09-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_external_chat_integration'),
        ('user', '0041_alter_account_id_alter_account_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.account'),
        ),
    ]
