# Generated by Django 5.2.5 on 2025-11-06 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_as_member', to='user.account')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_as_added_by', to='user.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.organization')),
            ],
        ),
    ]
