# Generated by Django 5.2.5 on 2025-11-06 15:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('ver_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('ver_code', models.CharField(default='87745', max_length=6)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
    ]
