# Generated by Django 5.2.5 on 2025-11-06 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='access_key',
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='pin',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='13725', max_length=6),
        ),
    ]
