# Generated by Django 5.2.5 on 2025-11-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_organization_access_key_organization_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='82189', max_length=6),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
