# Generated by Django 5.2.5 on 2025-11-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_organization_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='96235', max_length=6),
        ),
    ]
