# Generated by Django 5.2.5 on 2025-11-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='66051', max_length=6),
        ),
    ]
