# Generated by Django 5.2.5 on 2025-11-18 19:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='18719', max_length=6),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(default='0d1fae2ae2db665e69aada8bc6433270')),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
    ]
