# Generated by Django 5.2.5 on 2025-11-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_verification_ver_code_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='044f36eae15b27c793391393e69eac4b'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='38135', max_length=6),
        ),
    ]
