# Generated by Django 5.2.5 on 2025-11-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_token_token_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='eb9f202b469224360d9f119bb74be3a8'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='27616', max_length=6),
        ),
    ]
