# Generated by Django 5.2.5 on 2025-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_token_token_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='6708c00d86d5bd8f8175e63694384d78'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='95901', max_length=6),
        ),
    ]
