# Generated by Django 5.2.5 on 2025-11-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_token_token_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='d1363689ee5e8d7eecc8fb028ec8b819'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='74490', max_length=6),
        ),
    ]
