# Generated by Django 5.2.5 on 2025-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_token_token_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='6a95baf5ce32bb80c7ed4f7eb9d63042'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='52888', max_length=6),
        ),
    ]
