# Generated by Django 5.2.5 on 2025-12-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_token_token_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='1320a0cc1b956aa1486a9ef2114aafde'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='69906', max_length=6),
        ),
    ]
