# Generated by Django 5.2.5 on 2026-03-15 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_token_token_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='join_type',
            field=models.CharField(default='system', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='5e9e22173d412860d7d8f08cc826298d'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='23695', max_length=6),
        ),
    ]
