# Generated by Django 5.2.5 on 2026-09-13 09:30

import user.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_account_join_type_alter_account_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chatterloop_account_id',
            field=models.CharField(blank=True, default=None, help_text='chatterloop user_account.id, for correlating back.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='entity_id',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='The chatterloop entity this account mirrors.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the projection was last refreshed from chatterloop.', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Human-readable label for the integration/app this token belongs to.', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, default=uuid.uuid4, help_text='No longer read for sign-in - chatterloop owns credentials. Kept because auto-provisioned end-user rows still get one written.', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=user.models.generate_developer_token),
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
