"""
Django settings for neon project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

DB_HOST = os.getenv("DB_HOST")
DB_NAME = os.getenv("DB_NAME")
DB_PORT = os.getenv("DB_PORT")
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")

# Chatterloop's own Postgres. Neon reads identity from it (who somebody is,
# which pages they may act as) and writes bot/token rows into it. It is never
# migrated by Neon - see chatterloop/routers.py.
CHATTERLOOP_DB_HOST = os.getenv("CHATTERLOOP_DB_HOST")
CHATTERLOOP_DB_NAME = os.getenv("CHATTERLOOP_DB_NAME")
CHATTERLOOP_DB_PORT = os.getenv("CHATTERLOOP_DB_PORT", "5432")
CHATTERLOOP_DB_USERNAME = os.getenv("CHATTERLOOP_DB_USERNAME")
CHATTERLOOP_DB_PASSWORD = os.getenv("CHATTERLOOP_DB_PASSWORD")

# Where Neon forwards sign-in. No trailing slash.
CHATTERLOOP_API_BASE_URL = os.getenv(
    "CHATTERLOOP_API_BASE_URL", "https://api.chatterloop.app"
).rstrip("/")

# Where ANOTHER SERVICE reaches Neon.
#
# Used to build the /wake and /sleep webhook urls written into chatterloop's
# bot_commands. Those are called by chatterloop's worker_service, so the value
# has to be the address that worker can resolve - not localhost, and not a
# relative path. Left empty, the two commands are simply not provisioned and a
# warning says so, rather than rows being written that point nowhere.
NEON_PUBLIC_BASE_URL = os.getenv("NEON_PUBLIC_BASE_URL", "").rstrip("/")

# developer_service - the API Neon's BOTS authenticate against, with the clt_
# tokens minted in chatterloop/provisioning.py. A DIFFERENT service from
# CHATTERLOOP_API_BASE_URL above, which is user_service and handles sign-in.
# Empty until set: minting a bot works without it, and only /v1/whoami
# verification needs it, so an unset value fails one feature rather than
# blocking startup.
DEVELOPER_SERVICE_BASE_URL = os.getenv("DEVELOPER_SERVICE_BASE_URL", "").rstrip("/")

# Stamped onto the sign-in requests Neon makes on a user's behalf, so the
# device session chatterloop creates is recognisable in their own device list
# rather than appearing as an unexplained login.
CHATTERLOOP_USER_AGENT = os.getenv("CHATTERLOOP_USER_AGENT", "Neon Platform")

CHATTERLOOP_HTTP_TIMEOUT = float(os.getenv("CHATTERLOOP_HTTP_TIMEOUT", "15"))

# Encrypts credentials Neon must be able to read back - provider API keys, and
# later the chatterloop token secret. Deliberately NOT SECRET_KEY: rotating
# Django's secret should not make every stored credential unreadable.
# Generate: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
TOKEN_ENCRYPTION_KEY = os.getenv("TOKEN_ENCRYPTION_KEY")

# Previous keys, newest first, so a rotation is not a flag day. See
# neon/utils/crypto.py.
TOKEN_ENCRYPTION_KEY_FALLBACKS = [
    k for k in os.getenv("TOKEN_ENCRYPTION_KEY_FALLBACKS", "").split(",") if k.strip()
]

# Which organization existing Tool/Role rows belong to, for the migration that
# makes them organization-scoped. Only consulted when more than one
# organization exists - with exactly one, that one is unambiguous.
NEON_DEFAULT_ORGANIZATION_ID = os.getenv("NEON_DEFAULT_ORGANIZATION_ID")

DEBUG = os.getenv("DEBUG", "False").strip().lower() == "true"
SECRET_KEY = os.getenv("SECRET_KEY")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_USERNAME = os.getenv("REDIS_USERNAME")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")

MONGODB_CLUSTER_USER = os.getenv("MONGODB_CLUSTER_USER")
MONGODB_CLUSTER_PASS = os.getenv("MONGODB_CLUSTER_PASS")
MONGODB_CLUSTER_HOST = os.getenv("MONGODB_CLUSTER_HOST")
MONGODB_DB = os.getenv("MONGODB_DB")

MAILINGSERVICE = os.getenv("MAILINGSERVICE")

CSRF_TRUSTED_ORIGINS = ["https://*.chatterloop.app", "https://*.neonsystems.net"]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0",  # Change if needed
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "celery",
    # Added apps
    "user",
    "organization",
    "llm",
    "messenger",
    "core",
    "chatterloop",
]

MIDDLEWARE = [
    # SecurityMiddleware first, then WhiteNoise DIRECTLY after it - the order
    # WhiteNoise's own documentation asks for, so static responses carry the
    # security headers rather than bypassing them.
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # CORS has to run before anything that can generate a response, or a
    # preflight answered by CommonMiddleware goes out with no CORS headers on
    # it. It was below CommonMiddleware, which is the documented wrong place.
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Listed once. It was in here twice, so every request ran it twice.
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

RAG = {
    "PINECONE_API_KEY": os.getenv("PINECONE_API_KEY"),
    "PINECONE_INDEX": os.getenv("PINECONE_INDEX"),
    "EMBEDDING_MODEL": os.getenv("EMBEDDING_MODEL"),
    "DIMENSION": os.getenv("DIMENSION"),
    "CHUNK_SIZE": os.getenv("CHUNK_SIZE"),
    "RERANKER_MODEL": os.getenv("RERANKER_MODEL"),
    # How an organization's vectors are separated from everyone else's.
    #
    #   "dual"       - write to the organization's namespace, read that AND the
    #                  legacy default namespace, merged. The safe default: an
    #                  existing index keeps working while its vectors are moved.
    #   "namespaced" - read only the namespace. One query instead of two.
    #
    # Move from one to the other with `manage.py migrate_rag_namespaces`.
    # A fresh deployment pays nothing for "dual": the legacy read is skipped
    # automatically once the default namespace is seen to be empty.
    "NAMESPACE_MODE": os.getenv("RAG_NAMESPACE_MODE", "dual"),
}

# Celery (you already have Redis)
CELERY_BROKER_URL = (
    f"redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"
)

# No result backend: every task here is fire-and-forget indexing or answering,
# and nothing ever calls .get(). This used to be assigned twice - once to the
# Redis URL and again to None a few lines later - so the Redis value never took
# effect and reading the file suggested otherwise.
CELERY_RESULT_BACKEND = None
CELERY_IGNORE_RESULT = True
CELERY_STORE_ERRORS_EVEN_IF_IGNORED = False

CELERY_BROKER_POOL_LIMIT = 0
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Was 1, which recycled the worker process after EVERY task. That defeated the
# per-process RAG client in llm/scripts/tasks.py entirely - its whole purpose
# is to avoid a Pinecone list_indexes() round trip per task, and a process that
# lives for exactly one task caches nothing. Every indexing task paid full
# process startup plus that round trip.
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200

# ~390MB. The previous ~97MB was tight for a worker holding a Pinecone client,
# an OpenAI client and a text splitter at once, so children were being recycled
# on memory long before the task ceiling.
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 400000

CORS_ALLOWED_ORIGINS = []

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-access-token",
    "x-developer-token",
    # The organization a request acts in. Missing from this list, the browser
    # blocks the CORS preflight and EVERY tenant-scoped call fails before it
    # is sent - which looks like the API being down rather than a header
    # being unlisted.
    "x-organization",
    "paginated",
    "action",
]

ROOT_URLCONF = "neon.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "neon.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USERNAME,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    },
    "chatterloop": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": CHATTERLOOP_DB_NAME,
        "USER": CHATTERLOOP_DB_USERNAME,
        "PASSWORD": CHATTERLOOP_DB_PASSWORD,
        "HOST": CHATTERLOOP_DB_HOST,
        "PORT": CHATTERLOOP_DB_PORT,
        # Nothing in Neon should ever hold a transaction open against another
        # service's database while it thinks.
        "ATOMIC_REQUESTS": False,
    },
}

DATABASE_ROUTERS = ["chatterloop.routers.ChatterloopRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#
# WHY THE ADMIN HAD NO STYLING
# ----------------------------
# There was a STATIC_URL and a WhiteNoise middleware and nothing else: no
# STATIC_ROOT for `collectstatic` to write into, and no `collectstatic` step in
# the image. So the admin rendered its HTML perfectly and every stylesheet it
# asked for came back 404 - and because DEBUG is False, Django's development
# static handler was not there to paper over it either.
#
# The three pieces have to agree: somewhere to collect TO, something that
# collects, and something that serves. STATIC_ROOT and the storage below are
# the first and third; the Dockerfile runs the second.

STATIC_URL = "static/"

# Where `collectstatic` gathers everything WhiteNoise then serves. Inside the
# project directory rather than /var/..., so the same path works in the image,
# in a container and on a laptop.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Compressed but NOT hashed. The manifest variant is the usual
        # production recommendation and gives far-future caching, but it turns
        # a missing `collectstatic` into a 500 on every page that renders a
        # `{% static %}` tag rather than an unstyled one - and DEBUG is False
        # here even in local development, so that failure would be one command
        # away at all times. The admin is not worth that trade.
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "neon.backends.AutheticationBackend",
    ],
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]
